/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * File transfer handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.fileTransfer()`. Holds an `Arc<Node>` to create
 * fresh `FileTransfer` handles on each method call (the Rust `FileTransfer`
 * borrows `&Node`, so we can't store it across JS boundaries).
 */
export declare class NapiFileTransfer {
  /**
   * Send a file to a peer.
   *
   * `peer_id` is the recipient's stable `device_id` (RFC 017). The
   * underlying `resolve_peer_id` also accepts device names, prefixes,
   * and legacy Tailscale IDs. Resolves with transfer result on success.
   */
  sendFile(peerId: string, localPath: string, remotePath: string): Promise<NapiTransferResult>
  /**
   * Pull (download) a file from a remote peer.
   *
   * Resolves with transfer result on success.
   */
  pullFile(peerId: string, remotePath: string, localPath: string): Promise<NapiTransferResult>
  /** Auto-accept all incoming file offers, saving files to `output_dir`. */
  autoAccept(outputDir: string): Promise<void>
  /** Auto-reject all incoming file offers. */
  autoReject(): Promise<void>
  /**
   * Subscribe to incoming file offers with a callback.
   *
   * The callback receives a `NapiFileOffer`. Use `autoAccept()` or
   * `autoReject()` for automated handling, or use `onOffer()` for
   * manual inspection of offers.
   * Subscribe to incoming file offers with a callback.
   *
   * The callback receives `(offer, responder)` — call `responder.accept(path)`
   * or `responder.reject(reason)` to handle the offer. If neither is called
   * within 60 seconds, the offer is auto-rejected. Call `close()` on the
   * returned subscription to stop receiving offers.
   */
  onOffer(callback: (offer: FileOffer, responder: NapiOfferResponder) => void): NapiSubscription
  /**
   * Subscribe to file transfer events.
   *
   * The callback receives `NapiFileTransferEvent` objects for all
   * transfer lifecycle events (hashing, progress, completed, failed, etc.).
   * Call `close()` on the returned subscription to stop receiving events.
   */
  onEvent(callback: (event: FileTransferEvent) => void): NapiSubscription
  /** Set the maximum allowed transfer size in bytes. */
  setMaxTransferSize(bytes: number): void
  /**
   * Register a directory whose files may be served to peers on PULL_REQUEST.
   *
   * Pull-serving is deny-by-default: only files under a registered pull root
   * are served to peers. The path is canonicalized before registration.
   */
  addPullRoot(root: string): void
  /**
   * List the currently registered pull roots.
   *
   * Pull-serving is deny-by-default: only files under a registered pull root
   * are served to peers.
   */
  pullRoots(): Array<string>
  /**
   * Clear all registered pull roots.
   *
   * Pull-serving is deny-by-default: with no roots registered, no files are
   * served to peers.
   */
  clearPullRoots(): void
}

/**
 * The main truffle node exposed to JavaScript.
 *
 * Lifecycle:
 * 1. `new NapiNode()` — creates an empty wrapper.
 * 2. `await node.start(config)` — builds and starts the underlying `Node<TailscaleProvider>`.
 * 3. Use `getPeers()`, `send()`, `onPeerChange()`, etc.
 * 4. `await node.stop()` — shuts down the node.
 */
export declare class NapiNode {
  /** Create a new (unstarted) NapiNode. */
  constructor()
  /**
   * Install a callback to receive the Tailscale auth URL.
   *
   * Must be called BEFORE `start()`. During startup the Tailscale
   * provider may require interactive authentication; if so, this
   * callback is invoked with the auth URL while `start()` is still
   * waiting. If no callback is installed, `start()` uses the plain
   * build path and may reject with "timed out waiting for
   * authentication" after 5 minutes.
   */
  onAuthRequired(callback: (url: string) => void): void
  /**
   * Start the node with the given configuration.
   *
   * Resolves when the Tailscale sidecar is connected and the node is ready.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiNode while `start()` is in progress.
   */
  start(config: NapiNodeConfig): Promise<void>
  /**
   * Stop the node and release all resources.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiNode while `stop()` is in progress.
   */
  stop(): Promise<void>
  /** Get the local node's identity. */
  getLocalInfo(): NapiNodeIdentity
  /**
   * Get all known peers as plain snapshots (RFC 022 honest fields).
   *
   * Prefer {@link createMeshNode}'s wrapped `getPeers()` which returns
   * interned `Peer` handles with `===` identity. This native method
   * returns plain objects for low-level callers.
   */
  getPeers(): Promise<Array<NapiPeer>>
  /**
   * Resolve a query to a peer snapshot (RFC 022).
   *
   * Accepts display name, ULID, ULID prefix (≥4 unique chars), hostname,
   * Tailscale id, or tailnet IP. Not found → `null`. Ambiguous → throws.
   *
   * `waitMs`: block until resolvable or timeout (then `null`) — for
   * rehydrating a saved ULID before hello completes.
   */
  peer(query: string, waitMs?: number | undefined | null): Promise<NapiPeer | null>
  /**
   * Resolve a peer identifier (name or ID) to a routing string.
   *
   * @deprecated Prefer {@link peer} or Peer handles from `createMeshNode`.
   */
  resolvePeerId(peerId: string): Promise<string>
  /**
   * Ping a peer and return latency info.
   *
   * `peer_id` may be a ULID, name, Tailscale id, or IP (query string).
   */
  ping(peerId: string): Promise<NapiPingResult>
  /**
   * Tailnet identity (WhoIs) of the node that owns an address.
   *
   * `addr` accepts a raw tailnet IP or `ip:port` (e.g. a QUIC
   * connection's `remoteAddress()` verbatim — the port is ignored), or
   * any `resolvePeerId` identifier form for mesh peers. Unlike `peers()`,
   * a raw address reaches ANY tailnet device — other apps' truffle nodes,
   * plain machines, tagged nodes — and the answer carries user identity
   * (login, display name, profile pic) that peer entries deliberately do
   * not.
   *
   * Resolves `null` when the tailnet has no identity for the address:
   * absent, not fabricated. Requires a v3 sidecar (rejects on older ones).
   */
  whois(addr: string): Promise<NapiPeerIdentity | null>
  /** Get health information from the network layer. */
  health(): Promise<NapiHealthInfo>
  /**
   * Send a namespaced message to a specific peer.
   *
   * Legacy content-sniffing behavior: bytes that parse as UTF-8 JSON go
   * on the wire as that JSON value, anything else as a byte array.
   * Prefer `sendJson` / `sendBytes`, whose wire type never depends on
   * the data's contents.
   */
  send(peerId: string, namespace: string, data: Buffer): Promise<void>
  /** Send a JSON payload to a specific peer (explicit wire type). */
  sendJson(peerId: string, namespace: string, payload: any): Promise<void>
  /**
   * Send opaque binary data to a specific peer (explicit wire type).
   *
   * The bytes travel base64-encoded under the `"bytes"` msg_type — the
   * wire representation never depends on the data's contents.
   */
  sendBytes(peerId: string, namespace: string, data: Buffer): Promise<void>
  /**
   * Broadcast a namespaced message to all connected peers.
   *
   * Legacy content-sniffing behavior — prefer `broadcastJson` /
   * `broadcastBytes`, which also report queueing failures.
   */
  broadcast(namespace: string, data: Buffer): Promise<void>
  /**
   * Broadcast a JSON payload to all connected peers, reporting how many
   * peers it was queued to.
   */
  broadcastJson(namespace: string, payload: any): Promise<NapiBroadcastReport>
  /**
   * Broadcast opaque binary data to all connected peers, reporting how
   * many peers it was queued to.
   */
  broadcastBytes(namespace: string, data: Buffer): Promise<NapiBroadcastReport>
  /**
   * Open a raw TCP connection to a peer on the given port (RFC 021).
   *
   * `host` accepts a device id (or a unique ≥4-char prefix), device
   * name, Tailscale hostname, or Tailscale IP. The returned socket is
   * pull-model — see `NapiTcpSocket`; the `@vibecook/truffle` package
   * wraps it in a `stream.Duplex`.
   */
  openTcp(host: string, port: number): Promise<NapiTcpSocket>
  /**
   * Listen for raw TCP connections on a port (RFC 021).
   *
   * Port 0 binds an ephemeral port — read the resolved port from the
   * returned listener. The session WebSocket port (default 9417) is
   * reserved. Pass `tls: true` to terminate TLS in the sidecar with
   * automatic MagicDNS certificates (RFC 023 §7.1 — requires MagicDNS +
   * HTTPS enabled on the tailnet, and a sidecar built with RFC 023 for
   * port 443).
   */
  listenTcp(port: number, tls?: boolean | undefined | null): Promise<NapiTcpListener>
  /**
   * Bind a UDP datagram socket on a port (RFC 021).
   *
   * Datagram boundaries are preserved; keep payloads ≤ ~1,200 bytes
   * (tailnet MTU). Port 0 binds an ephemeral relay port — suitable for
   * client-style sockets that send first.
   */
  bindUdp(port: number): Promise<NapiUdpSocket>
  /**
   * Open a raw QUIC connection to a peer on the given port (RFC 021).
   *
   * The connection carries multiple concurrent bidirectional byte
   * streams with no head-of-line blocking. Only same-app peers can
   * complete the handshake (ALPN scoping). `host` accepts the same
   * identifier forms as `openTcp`.
   */
  connectQuic(host: string, port: number): Promise<NapiQuicConnection>
  /**
   * Listen for raw QUIC connections on a port (RFC 021).
   *
   * Ports 443 and 9417 are reserved; port 0 is not supported over the
   * tsnet relay — choose an explicit port.
   */
  listenQuic(port: number): Promise<NapiQuicListener>
  /**
   * Subscribe to peer change events.
   *
   * The callback receives `NapiPeerEvent` objects whenever peers
   * join, leave, connect, disconnect, or update. Call `close()` on the
   * returned subscription to stop receiving events.
   */
  onPeerChange(callback: (event: PeerEvent) => void): NapiSubscription
  /**
   * Subscribe to messages on a specific namespace.
   *
   * The callback receives `NapiNamespacedMessage` objects. Call `close()`
   * on the returned subscription to stop receiving messages.
   */
  onMessage(namespace: string, callback: (msg: NamespacedMessage) => void): NapiSubscription
  /** Get a `NapiFileTransfer` handle for file transfer operations. */
  fileTransfer(): NapiFileTransfer
  /** Get a `NapiProxy` handle for reverse proxy operations. */
  proxy(): NapiProxy
  /**
   * Get a `NapiSyncedStore` handle for synchronized state operations.
   *
   * Each call creates a new store instance with the given `store_id`.
   * Multiple stores can coexist with different IDs.
   */
  syncedStore(storeId: string): NapiSyncedStore
}

/**
 * Responder for accepting or rejecting a file offer from JS.
 *
 * The responder is consumed on the first call to `accept()` or `reject()`.
 * If neither is called, the offer times out after 60 seconds.
 */
export declare class NapiOfferResponder {
  /** Accept the file offer, saving to the specified path. */
  accept(savePath: string): Promise<void>
  /** Reject the file offer with a reason. */
  reject(reason: string): Promise<void>
}

/**
 * Reverse proxy handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.proxy()`. Holds an `Arc<Node>` to create
 * fresh `Proxy` handles on each method call (the Rust `Proxy` borrows
 * `&Node`, so we can't store it across JS boundaries).
 */
export declare class NapiProxy {
  /**
   * Add a reverse proxy that forwards traffic from a TLS port on the mesh
   * to a local target.
   */
  add(config: NapiProxyConfig): Promise<NapiProxyInfo>
  /** Remove a reverse proxy by ID. */
  remove(id: string): Promise<void>
  /** List all active proxies on this node. */
  list(): Promise<Array<NapiProxyInfo>>
  /**
   * Subscribe to proxy lifecycle events.
   *
   * The callback receives `NapiProxyEvent` objects whenever a proxy
   * starts, stops, or encounters an error. Call `close()` on the returned
   * subscription when the listener is no longer needed.
   */
  onEvent(callback: (event: NapiProxyEvent) => void): NapiSubscription
}

/**
 * A raw QUIC connection to a peer over the mesh.
 *
 * Open streams with `openStream()`; accept peer-opened streams with
 * `acceptStream()` (resolves `null` once the connection closes). Streams
 * are lazy — the peer's accept does not fire until the opener writes.
 */
export declare class NapiQuicConnection {
  /** Open a new bidirectional byte stream on this connection. */
  openStream(): Promise<NapiQuicStream>
  /**
   * Accept the next stream the peer opens.
   *
   * Resolves `null` once the connection has closed (either side).
   */
  acceptStream(): Promise<NapiQuicStream | null>
  /** The peer's tailnet address (`100.x.x.x:port` over the relay). */
  remoteAddress(): string
  /**
   * The peer's stable device id when known. `null` means "anonymous but
   * tailnet-authenticated".
   */
  remotePeerId(): string | null
  /**
   * The peer's full WhoIs identity — the tailnet's answer about the
   * connection's WireGuard-authenticated remote address, never anything
   * the stream claims about itself. Reaches ANY tailnet caller, not just
   * mesh peers, and works on outbound connections too.
   *
   * Resolved lazily on first call — `accept()` never blocks on identity —
   * and cached for the connection's lifetime. `null` for anonymous
   * callers, on pre-v3 sidecars, and when the lookup fails; failures are
   * not cached, so calling again retries (use `node.whois()` to
   * distinguish "anonymous" from "lookup failed").
   */
  remoteIdentity(): Promise<NapiPeerIdentity | null>
  /** Close the connection and all its streams. Idempotent. */
  close(): void
}

/** A listener for raw QUIC connections on a mesh port. */
export declare class NapiQuicListener {
  /**
   * Accept the next incoming connection.
   *
   * Resolves `null` once the listener has been closed. Cross-app
   * connection attempts fail the TLS handshake (ALPN scoping) and are
   * skipped, never surfaced.
   */
  accept(): Promise<NapiQuicConnection | null>
  /** The port this listener is bound to. */
  port(): number
  /**
   * Close the listener and connections accepted from it. Pending
   * `accept()` calls resolve with `null`. Idempotent.
   */
  close(): void
}

/**
 * A bidirectional byte stream on a QUIC connection.
 *
 * Behaves like an independent TCP connection (ordered, reliable,
 * flow-controlled) without head-of-line blocking against sibling streams.
 * Pull-model reads, like `NapiTcpSocket`.
 */
export declare class NapiQuicStream {
  /**
   * Read up to `maxBytes` (default 64 KiB) from the stream.
   *
   * Resolves with the next chunk, or `null` on clean EOF (the peer
   * finished the stream) and after `close()`.
   */
  read(maxBytes?: number | undefined | null): Promise<Buffer | null>
  /** Write all of `data` to the stream (respects QUIC flow control). */
  write(data: Buffer): Promise<void>
  /**
   * Half-close: finish the write side, signalling clean EOF to the
   * peer. Reading remains possible. Idempotent.
   */
  finish(): Promise<void>
  /**
   * Fully close the stream (finish writes, stop reads). Unblocks any
   * pending `read()` (it resolves `null`). Idempotent.
   */
  close(): Promise<void>
}

/**
 * A live native callback subscription.
 *
 * Call `close()` when the listener is no longer needed. Closing is
 * idempotent. For backwards compatibility, ignoring the returned handle
 * leaves the listener active until its owning node/store stops.
 */
export declare class NapiSubscription {
  /** Stop forwarding events to the callback. Idempotent. */
  close(): void
}

/**
 * Synchronized store handle exposed to JavaScript.
 *
 * Obtained via `NapiNode.syncedStore(storeId)`. Each store instance manages
 * device-owned slices of JSON data that are automatically synchronized
 * across the mesh.
 */
export declare class NapiSyncedStore {
  /** Update this device's data in the store. */
  set(data: any): Promise<void>
  /** Get this device's current data, or `null` if `set()` hasn't been called. */
  local(): Promise<any | null>
  /** Get a specific peer's slice by device ID. */
  get(deviceId: string): Promise<NapiSlice | null>
  /** Get all slices (local + remote) as an array. */
  all(): Promise<Array<NapiSlice>>
  /** Get all device IDs that have data in this store. */
  deviceIds(): Promise<Array<string>>
  /** The store identifier. */
  storeId(): string
  /** Current local version number. */
  version(): number
  /**
   * Subscribe to store change events.
   *
   * The callback receives `NapiStoreEvent` objects whenever local data
   * changes, a peer's data is updated, or a peer is removed. Call `close()`
   * on the returned subscription when the listener is no longer needed.
   */
  onChange(callback: (event: StoreEvent) => void): NapiSubscription
  /**
   * Stop the store and cancel all event-forwarding tasks.
   *
   * # Safety
   * This takes `&mut self` in an async context. The caller must ensure that
   * no other calls are made on this NapiSyncedStore while `stop()` is in progress.
   */
  stop(): Promise<void>
}

/** A listener for raw TCP connections on a mesh port. */
export declare class NapiTcpListener {
  /**
   * Accept the next incoming connection.
   *
   * Resolves with `null` once the listener has been closed.
   */
  accept(): Promise<NapiTcpSocket | null>
  /** The port this listener is bound to (resolved when 0 was requested). */
  port(): number
  /**
   * Close the listener and release the tsnet port in the sidecar.
   * Pending `accept()` calls resolve with `null`. Idempotent.
   */
  close(): Promise<void>
}

/**
 * A raw TCP connection to a peer over the mesh.
 *
 * Reads are pull-model: `read()` resolves with the next chunk, `null` on
 * clean EOF. Writes resolve once the bytes are handed to the transport
 * (respecting backpressure). `end()` half-closes the write side (FIN);
 * `close()` tears down both directions. Dropping the JS object without
 * closing also closes the socket (no background tasks are held).
 */
export declare class NapiTcpSocket {
  /**
   * Read up to `maxBytes` (default 64 KiB) from the socket.
   *
   * Resolves with the next chunk of data, or `null` on clean EOF (the
   * peer finished writing) and after `close()`.
   */
  read(maxBytes?: number | undefined | null): Promise<Buffer | null>
  /** Write all of `data` to the socket. */
  write(data: Buffer): Promise<void>
  /**
   * Half-close the write side (send FIN), like `socket.end()`.
   *
   * Reading remains possible until the peer closes its side. Idempotent.
   */
  end(): Promise<void>
  /**
   * Fully close the socket (both directions). Unblocks any pending
   * `read()` (it resolves `null`). Idempotent.
   */
  close(): Promise<void>
  /**
   * The logical remote address (`host:port` for outbound connections,
   * the peer's tailnet address for inbound ones).
   */
  remoteAddress(): string
  /**
   * The peer's stable id when known — the resolved device id for
   * outbound connections, the WhoIs node id for inbound ones. `null`
   * means "anonymous but tailnet-authenticated" (never gate on it).
   */
  remotePeerId(): string | null
  /**
   * Human-readable peer name from the WhoIs identity (inbound only).
   *
   * Provenance is indeterminate — it may be a display name, a login, or a
   * DNS name. Prefer `remoteIdentity()` when the distinction matters.
   */
  remotePeerName(): string | null
  /**
   * The peer's full WhoIs identity (inbound only): DNS name, login,
   * display name, profile pic, node id — each individually optional.
   * `null` for outbound sockets and anonymous callers.
   */
  remoteIdentity(): NapiPeerIdentity | null
}

/**
 * A UDP socket on the mesh.
 *
 * Datagram boundaries are preserved end-to-end. Keep payloads ≤ ~1,200
 * bytes to stay under the tailnet MTU (larger datagrams fragment in the
 * userspace netstack and become loss-prone). IPv4 (`100.x`) peers only.
 */
export declare class NapiUdpSocket {
  /**
   * Send a datagram to `host:port`.
   *
   * `host` accepts a peer's device id (or unique ≥4-char prefix),
   * device name, Tailscale hostname, or Tailscale IP. Resolves with
   * the number of payload bytes sent.
   */
  send(data: Buffer, host: string, port: number): Promise<number>
  /**
   * Receive the next datagram.
   *
   * Resolves `null` once the socket has been closed. Note UDP is
   * unreliable: datagrams may be dropped or reordered.
   */
  recv(): Promise<NapiDatagram | null>
  /**
   * The mesh port this socket is bound to (the tsnet port over the
   * relay; 0 for ephemeral client-style sockets whose tsnet port is
   * unknown — see RFC 021).
   */
  port(): number
  /**
   * Close the socket. Any in-flight `recv()` resolves with `null`.
   * Idempotent.
   */
  close(): void
}

/**
 * Snapshot fields mirrored onto the JS `Peer` class.
 *
 * Getters read from this snapshot; call [`Peer::refresh_from`] when the
 * registry updates the peer so live fields stay current without reallocating
 * the JS object (preserving `===`).
 */
export declare class Peer {
  /**
   * Process-local opaque ref — safe Map key when object identity is
   * inconvenient; do not persist across restarts.
   */
  get peerRef(): string
  /** Best label for UI. */
  get displayName(): string
  /** Durable ULID once known; `null` until identity is learned. */
  get deviceId(): string | null
  /** Human-readable name from hello identity, if known. */
  get deviceName(): string | null
  /** Layer 3 Tailscale hostname. */
  get hostname(): string
  /** Tailscale stable node id (advanced / routing diagnostics). */
  get tailscaleId(): string
  /** Registry generation (bumped on re-join). */
  get generation(): number
  get ip(): string
  get online(): boolean
  /** Envelope-bus WebSocket up. Advanced — do not gate `send` on this. */
  get wsConnected(): boolean
  get connectionType(): string
  get os(): string | null
  get lastSeen(): string | null
  /** Same registry entry generation (RFC 022 §7.7). */
  equals(other: Peer): boolean
  /**
   * Send a namespaced message to this peer.
   *
   * Legacy content-sniffing behavior — prefer `sendJson` / `sendBytes`.
   */
  send(namespace: string, data: Buffer): Promise<void>
  /** Send a JSON payload to this peer (explicit wire type). */
  sendJson(namespace: string, payload: any): Promise<void>
  /**
   * Send opaque binary data to this peer (explicit wire type; base64
   * `"bytes"` envelope — never depends on the data's contents).
   */
  sendBytes(namespace: string, data: Buffer): Promise<void>
  /** Ping this peer. */
  ping(): Promise<NapiPingResult>
}

/**
 * Outcome of a `broadcastJson` / `broadcastBytes` call.
 *
 * "Queued" means handed to a peer's connection task — not confirmed
 * delivery. Broadcasts reach only currently connected peers.
 */
export interface NapiBroadcastReport {
  /** Peers with an active WS connection at broadcast time. */
  attempted: number
  /** Messages successfully queued to a connection task. */
  queued: number
  /** Tailscale ids of peers whose connection task was already closed. */
  failed: Array<string>
}

/** A datagram received from the mesh. */
export interface NapiDatagram {
  data: Buffer
  /** Sender's tailnet IP (`100.x.x.x`) — WireGuard-authenticated. */
  address: string
  /** Sender's source port. */
  port: number
}

/** An incoming file offer from a remote peer. */
export interface NapiFileOffer {
  /**
   * Sender's WhoIs-verified **Tailscale stable id** (RFC 022 §7.5
   * attribution). NOT the durable ULID: allowlists must compare against
   * `peer.tailscaleId`, not `peer.deviceId`.
   */
  fromPeer: string
  /** Human-readable device name of the sending peer. */
  fromName: string
  /** File name being offered. */
  fileName: string
  /** File size in bytes. */
  size: number
  /** Expected SHA-256 hash (hex). */
  sha256: string
  /** Suggested save path from the sender. */
  suggestedPath: string
  /** Unique token for this transfer. */
  token: string
}

/** Events emitted by the file transfer subsystem. */
export interface NapiFileTransferEvent {
  /**
   * Event type: "offer_received", "hashing", "waiting_for_accept",
   * "progress", "completed", "rejected", "failed".
   */
  eventType: string
  /** Transfer token (if applicable). */
  token?: string
  /** File name (if applicable). */
  fileName?: string
  /** Direction: "send" or "receive" (if applicable). */
  direction?: string
  /** Progress info (present for "progress" events). */
  progress?: NapiTransferProgress
  /** Offer info (present for "offer_received" events). */
  offer?: NapiFileOffer
  /** Bytes transferred (present for "completed" events). */
  bytesTransferred?: number
  /** SHA-256 hash (present for "completed" events). */
  sha256?: string
  /** Elapsed seconds (present for "completed" events). */
  elapsedSecs?: number
  /** Reason for rejection or failure. */
  reason?: string
  /** Bytes hashed so far (present for "hashing" events). */
  bytesHashed?: number
  /** Total bytes to hash (present for "hashing" events). */
  totalBytes?: number
}

/** Health information from the network layer. */
export interface NapiHealthInfo {
  /** Current backend state (e.g., "Running", "NeedsLogin"). */
  state: string
  /** Key expiry timestamp (RFC 3339), if applicable. */
  keyExpiry?: string
  /** Active health warnings. */
  warnings: Array<string>
  /** Whether the network is fully operational. */
  healthy: boolean
}

/** A message received on a specific namespace. */
export interface NapiNamespacedMessage {
  /**
   * Sender's WhoIs-verified **Tailscale stable id** — the connection's
   * authenticated routing key (RFC 022 §7.5). NOT the durable ULID:
   * compare against `peer.tailscaleId`, or use `createMeshNode`'s
   * `onMessage`, whose `msg.from` is an interned `Peer` handle.
   */
  from: string
  /** Namespace the message was sent on. */
  namespace: string
  /** Application-defined message type. */
  msgType: string
  /** Opaque JSON payload (as a JS value via serde). */
  payload: any
  /** Millisecond Unix timestamp from the sender, if set. */
  timestamp?: number
}

/** Configuration for starting a Node (RFC 017 §7 shape). */
export interface NapiNodeConfig {
  /**
   * Application namespace identifier. Required. Must match
   * `^[a-z][a-z0-9-]{1,31}$`; validated on the Rust side.
   */
  appId: string
  /**
   * Optional human-readable device name. Defaults to the OS hostname.
   * May contain any Unicode characters; the Tailscale hostname is
   * derived automatically.
   */
  deviceName?: string
  /**
   * Optional stable ULID override. Auto-generated (and persisted) when
   * omitted.
   */
  deviceId?: string
  /**
   * Optional explicit Tailscale hostname (RFC 023 §6.4), bypassing the
   * `truffle-{appId}-{slug}` convention for pretty serving URLs. Must be
   * a single lowercase DNS label (1–63 chars of `[a-z0-9-]`, no dots).
   * Tradeoff: hello-less peers with a custom hostname lose bare
   * device-name resolution; read the granted name from
   * `getLocalInfo().dnsName` (Tailscale dedupes collisions with `-1`/`-2`).
   */
  hostname?: string
  /**
   * Tailscale state directory. Defaults to
   * `{userDataDir}/truffle/{app_id}/{slug(device_name)}`.
   */
  stateDir?: string
  /** Path to the Go sidecar binary. */
  sidecarPath: string
  /** Tailscale auth key for headless authentication. */
  authKey?: string
  /** Whether the node is ephemeral (auto-removed from tailnet on shutdown). */
  ephemeral?: boolean
  /** WebSocket listen port. Defaults to 9417. */
  wsPort?: number
  /**
   * RFC 022 Phase C: proactively exchange hello with online peers so
   * durable deviceId is learned without app send. Defaults to true.
   */
  eagerIdentity?: boolean
}

/** Identity of the local node (RFC 017 §7.2). */
export interface NapiNodeIdentity {
  /** Application namespace identifier. */
  appId: string
  /**
   * This node's own stable ULID (RFC 017 §5.4). Primary key for device
   * identity. Always the real ULID — unlike a *peer's* `deviceId` (see
   * `NapiPeer`), which falls back to a Tailscale id until that peer's
   * hello is seen. Persists across restarts, including with
   * `ephemeral: true`.
   */
  deviceId: string
  /** Original (unsanitised) device name, as passed by the application. */
  deviceName: string
  /** The Tailscale hostname (`truffle-{appId}-{slug}`). Debug use only. */
  tailscaleHostname: string
  /**
   * This node's Tailscale stable node ID. Escape hatch for diagnostics;
   * with `ephemeral: true` it rotates on each restart while `deviceId`
   * persists.
   */
  tailscaleId: string
  /** DNS name on the tailnet, if available. */
  dnsName?: string
  /** Tailscale IP address as a string, if available. */
  ip?: string
}

/** A peer as seen by application code (RFC 022 honest projection). */
export interface NapiPeer {
  /**
   * Durable ULID once known; `null` until identity is learned.
   * Never equals `tailscaleId` and never silently falls back to it.
   */
  deviceId?: string
  /** Human-readable device name from the hello identity block, if known. */
  deviceName?: string
  /** Best label for UI (identity name → hostname slug → short id). */
  displayName: string
  /** Layer 3 Tailscale hostname (`truffle-{appId}-{slug}`). */
  hostname: string
  /** Network IP address as a string. */
  ip: string
  /** Whether the peer is online (from Layer 3). */
  online: boolean
  /**
   * Whether an envelope-bus WebSocket session is currently open.
   * Advanced: do not gate `send` on this field.
   */
  wsConnected: boolean
  /** Connection type description (e.g., "direct" or "relay:ord"). */
  connectionType: string
  /** Operating system, if known. */
  os?: string
  /** Last time the peer was seen online (RFC 3339 string). */
  lastSeen?: string
  /** Tailscale stable node id — routing key / diagnostics (advanced). */
  tailscaleId: string
  /** Process-local ref `{tailscaleId}:{generation}` (RFC 022). */
  peerRef: string
  /** Registry entry generation (bumped on re-join). */
  generation: number
}

/** A peer change event delivered to JS. */
export interface NapiPeerEvent {
  /**
   * Event type: "joined", "left", "updated", "identity", "ws_connected",
   * "ws_disconnected", "auth_required".
   */
  eventType: string
  /**
   * Routing key of the affected peer (Tailscale stable id), or empty for
   * `auth_required`. Prefer `peer` when present (RFC 022).
   */
  peerId: string
  /**
   * Full peer info when available (joined/updated/identity; also preferred
   * on ws_* when resolvable).
   */
  peer?: NapiPeer
  /** Auth URL (present only for auth_required events). */
  authUrl?: string
}

/**
 * A tailnet WhoIs identity: the control plane's answer about who owns an
 * address. This is transport-derived — never a peer's claim about itself.
 *
 * Every field is optional: tagged nodes carry node identity but no user
 * profile, and legacy sidecars may omit fields. A fully anonymous caller has
 * no identity at all (`whois` resolves `null` instead).
 */
export interface NapiPeerIdentity {
  /** MagicDNS name (e.g. "kitchen.tail1234.ts.net"), trailing dot stripped. */
  dnsName?: string
  /** Tailscale login (owner) name, e.g. "alice@example.com". */
  loginName?: string
  /** Human-readable display name from the identity provider. */
  displayName?: string
  /** URL of the owner's profile picture. */
  profilePicUrl?: string
  /** Stable Tailscale node id (WhoIs `Node.StableID`). */
  nodeId?: string
}

/** Result of a network-level ping. */
export interface NapiPingResult {
  /** Round-trip latency in milliseconds. */
  latencyMs: number
  /** Connection type description (e.g., "direct" or "relay:sfo"). */
  connection: string
  /** Direct peer endpoint address, if available. */
  peerAddr?: string
}

/** Configuration for adding a reverse proxy, received from JavaScript. */
export interface NapiProxyConfig {
  /** Unique identifier (user-chosen or auto-generated). */
  id: string
  /** Human-readable name for the proxy. */
  name: string
  /** Port on which the proxy listens on the tailnet (NAPI uses i32). */
  listenPort: number
  /** Target host (default: "localhost"). */
  targetHost?: string
  /** Target port (the local service port). */
  targetPort: number
  /** Target scheme: "http" or "https" (default: "http"). */
  targetScheme?: string
  /** Whether to announce this proxy on the mesh for discovery (default: true). */
  announce?: boolean
  /**
   * Terminate TLS on the tailnet listener (default: true — the v1
   * always-TLS behavior). `false` = plain HTTP; requires a v2 sidecar.
   */
  tls?: boolean
  /**
   * Permit non-loopback targets (default: false — deny). A LAN target
   * turns this node into a pivot into its network (RFC 023 §9.3).
   */
  allowNonLoopback?: boolean
  /**
   * loginName allow globs, e.g. `["*@corp.com"]` (default: none = the
   * whole tailnet). Non-matching callers get a bare 403 (RFC 023 §9.7).
   */
  allow?: Array<string>
  /**
   * Path-prefix routes (RFC 023 §7). When non-empty they replace the
   * single `targetHost`/`targetPort`/`targetScheme` target.
   */
  routes?: Array<NapiProxyRoute>
}

/** A proxy lifecycle event delivered to JavaScript. */
export interface NapiProxyEvent {
  /** Event type: "started", "stopped", "error". */
  eventType: string
  /** Proxy ID. */
  id: string
  /** Fully qualified URL (present for "started" events). */
  url?: string
  /** Listen port (present for "started" events). */
  listenPort?: number
  /** Error code (present for "error" events). */
  code?: string
  /** Error message (present for "error" events). */
  message?: string
}

/** Information about a running or configured proxy, returned to JavaScript. */
export interface NapiProxyInfo {
  id: string
  name: string
  listenPort: number
  targetHost: string
  targetPort: number
  targetScheme: string
  url: string
  /** Status: "starting", "running", "stopped", or "error: <message>". */
  status: string
}

/**
 * One path-prefix route of a v2 proxy (RFC 023 §7). Exactly one of
 * `targetUrl` / `dir` is set; longest prefix wins. Validation lives in
 * core `validate_config`, not here.
 */
export interface NapiProxyRoute {
  /** Path prefix to match (must start with "/"). */
  prefix: string
  /**
   * Proxy target URL, e.g. "http://localhost:8000". Mutually exclusive
   * with `dir`.
   */
  targetUrl?: string
  /**
   * Static directory to serve (absolute path on the serving machine).
   * Mutually exclusive with `targetUrl`.
   */
  dir?: string
  /**
   * SPA fallback rewritten on static misses, e.g. "/index.html". Only
   * meaningful with `dir`.
   */
  fallback?: string
  /**
   * Strip the matched prefix before proxying (default: false). Only
   * meaningful with `targetUrl`.
   */
  stripPrefix?: boolean
  /**
   * Per-route loginName globs; overrides the config-level `allow`
   * (default: none = inherit).
   */
  allow?: Array<string>
}

/** A versioned slice of data owned by a single device. */
export interface NapiSlice {
  /**
   * Owning device's stable `device_id` (ULID) from the RFC 017 hello
   * envelope.
   */
  deviceId: string
  /** The data (JSON value). */
  data: any
  /** Monotonically increasing version (per-device). */
  version: number
  /** When this version was created (Unix milliseconds). */
  updatedAt: number
}

/** A store change event delivered to JS. */
export interface NapiStoreEvent {
  /** Event type: "local_changed", "peer_updated", "peer_removed". */
  eventType: string
  /**
   * Stable `device_id` (ULID) of the affected device (present for
   * peer_updated / peer_removed events).
   */
  deviceId?: string
  /** Data payload (present for local_changed/peer_updated events). */
  data?: any
  /** Version number (present for peer_updated events). */
  version?: number
}

/** Progress update for an in-flight file transfer. */
export interface NapiTransferProgress {
  /** Unique token for this transfer. */
  token: string
  /** Direction: "send" or "receive". */
  direction: string
  /** File name being transferred. */
  fileName: string
  /** Bytes transferred so far. */
  bytesTransferred: number
  /** Total file size in bytes. */
  totalBytes: number
  /** Current transfer speed in bytes per second. */
  speedBps: number
}

/** Result of a completed file transfer. */
export interface NapiTransferResult {
  /** Number of bytes transferred. */
  bytesTransferred: number
  /** SHA-256 hash of the transferred file. */
  sha256: string
  /** Elapsed time in seconds. */
  elapsedSecs: number
}
